### ISSUE TITLE
cap3 and error with empty contig files

### ISSUE THREAD

**Issue by varunaggarwala** [eclarke/sunbeam#39] opened 2016-12-22 16:08 UTC
If IDBA-ud does not generate a contig, then the followup program cap3 (which needs the contigs from IDBA-ud to further process them) gives an error.
Perhaps always creating a file from IDBA-ud can help solve this problem.

**Comment by eclarke** [comment] 2016-12-23 15:41
Can you provide examples of samples that do not yield contigs from IDBA-UD? This should trigger a MissingOutputException in Snakemake and not execute the CAP3 step.

**Comment by ArwaAbbas** [comment] 2016-12-25 01:46
I've also encountered this issue. This happened in a negative control sample (PCR water).
My fix is to specify that that sample should be excluded in the config file.

**Comment by eclarke** [comment] 2016-12-25 04:29
Can you guys post a traceback off the error message that you get, and possibly a test file?

**Comment by ArwaAbbas** [comment] 2016-12-25 14:08
An example of a sample that doesn't build contigs with IDBA-UD can be found here: 
microb120:/media/THING2/arwa/17_CTOT_Longitudinal/FilteredFASTQ/PCMP_H20NegCtrl1_D_R*

The error messages that appear are thus:
Error in job cap3 while creating output file /home/arwa/17_CTOT_Longitudinal/sunbeam_output/assembly/cap3/H20NegCtrl1_D/cap3-contigs.fa.

RuleException:
CalledProcessError in line 48 of /home/arwa/17_CTOT_Longitudinal/sunbeam/rules/assembly/assembly.rules:
Command '
        /home/arwa/17_CTOT_Longitudinal/sunbeam/local/CAP3/cap3 /home/arwa/17_CTOT_Longitudinal/sunbeam_output/assembly/idba_ud/H20NegCtrl1_D/contig.fa &> /home/arwa/17_CTOT_Longitudinal/sunbeam_output/assembly/log/cap3/H20NegCtrl1_D.out &&         cat /home/arwa/17_CTOT_Longitudinal/sunbeam_output/assembly/idba_ud/H20NegCtrl1_D/contig.fa.cap.singlets /home/arwa/17_CTOT_Longitudinal/sunbeam_output/assembly/idba_ud/H20NegCtrl1_D/contig.fa.cap.contigs > /home/arwa/17_CTOT_Longitudinal/sunbeam_output/assembly/cap3/H20NegCtrl1_D/cap3-contigs.fa
        ' returned non-zero exit status 139
  File "/home/arwa/17_CTOT_Longitudinal/sunbeam/rules/assembly/assembly.rules", line 48, in __rule_cap3
  File "/home/arwa/miniconda3/envs/sunbeam/lib/python3.5/concurrent/futures/thread.py", line 55, in run

**Comment by ressy** [comment] 2017-06-22 18:53
I have what should be a simple workaround for this, but my tests are failing because apparently there's a new snakemake version available for Anaconda and that's causing trouble for some existing rules on Travis.  I'm trying to reproduce that issue locally, and then I should be able to make the tests pass and provide a fix for this.

**Comment by eclarke** [comment] 2017-06-22 18:55
I think we should specify our specific version of snakemake in the conda requirements.txt if there's a breaking API change. We can move towards updating it later but it should be as a separate effort.

**Comment by ressy** [comment] 2017-06-22 20:28
Makes sense.  I'll figure out what the latest working version is and list that in the requirements.

**Comment by ressy** [comment] 2017-06-23 14:58
OK, I'm putting in a change to requirements.txt separately for #74, and then once that's settled so tests work correctly, I'll finish this one.

**Closed** 2017-06-23 19:26 UTC
